<%@ Page Language="VB" AutoEventWireup="false" CodeFile="input_hospital_2.aspx.vb" Inherits="modules_hr_input_hospital_2" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>Untitled Page</title>
    <link href="../../StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <table border="0" width="100%">
            <tr>
                <td colspan="2">
						<asp:Label ID="lblHeader" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Edit Previous Hospital Visits"></asp:Label></td>
            </tr>
            <tr>
                <td width="3%">&nbsp;
                    </td>
                <td>
        <asp:GridView ID="gvMaster" runat="server" CssClass="noBorderedMenuTable" 
                    AllowPaging="True" AutoGenerateColumns="False" 
                    DataKeyNames="StaffId" DataSourceID="dsoUsers" AllowSorting="True" 
                    CellPadding="4" ForeColor="#333333" GridLines="None" Width="1000px" 
                        SelectedIndex="0" >
            <Columns>
                <asp:TemplateField HeaderText="Staff Code" SortExpression="StaffCode">
                    <EditItemTemplate>
                        <asp:Label ID="TextBox47" runat="server" Text='<%# Bind("StaffCode") %>'></asp:Label>
                   </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label49" runat="server" Text='<%# Bind("StaffCode") %>'></asp:Label>
                    </ItemTemplate>
                    <ItemStyle Width="70px" />
                </asp:TemplateField>
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:Image ID="Image1" runat="server" Height="30px" 
                        ImageUrl='<%# "..\..\_uploads\photos\photo_" & Databinder.Eval(Container.DataItem, "StaffGUID").ToString & ".jpg" %>' 
                        Width="30px" BorderColor="Black" BorderStyle="Solid" BorderWidth="2px" /><br /><asp:Label ID="Label49_2" runat="server" Text='<%# Databinder.Eval(Container.DataItem, "Surname").ToString.ToUpper & " " & Databinder.Eval(Container.DataItem, "OtherNames").ToString.ToUpper %>'></asp:Label>
                    </ItemTemplate>
                    <ItemStyle Width="60px" />
                </asp:TemplateField>
                <asp:CommandField SelectText="Show Hospital Visits" ShowSelectButton="True">
                <ItemStyle Width="80px" />
                </asp:CommandField>
                <asp:TemplateField HeaderText="HOSPITAL VISITS">
                    <ItemTemplate>
                        <asp:GridView ID="gvDetail" runat="server" AllowSorting="True" 
                            AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                            AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CellPadding="4" 
                            CssClass="noBorderedMenuTable" DataKeyNames="StaffMedicalId" 
                            DataSourceID="dsSqlGetDetail" 
                            EmptyDataText="&amp;nbsp;&lt;br /&gt;No records to display.&lt;br /&gt;&amp;nbsp;" 
                            ForeColor="#333333" GridLines="None" Visible="False" Width="100%" 
                            Font-Bold="False">
                            <Columns>
                                <asp:BoundField DataField="StaffMedicalId" HeaderText="Id" 
                                    InsertVisible="False" ReadOnly="True" SortExpression="StaffMedicalId" />
                                <asp:TemplateField HeaderText="Staff Id" SortExpression="StaffId">
                                    <EditItemTemplate>
                                        <asp:Label ID="Label11" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label20" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Hospital" SortExpression="HospitalId">
                                    <EditItemTemplate>
                                        <asp:DropDownList ID="DropDownList8" runat="server" 
                                            CssClass="defaultFormElementStyle" DataSourceID="dsSqlHospitals2" 
                                            DataTextField="HospitalName" DataValueField="HospitalId" 
                                            SelectedValue='<%# Bind("HospitalId") %>'>
                                        </asp:DropDownList>
                                        <asp:SqlDataSource ID="dsSqlHospitals2" runat="server" 
                                            ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                            SelectCommand="SELECT [HospitalId], [HospitalName] FROM [HR_Hospital] ORDER BY [HospitalName]">
                                        </asp:SqlDataSource>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label8" runat="server" Text='<%# Bind("HospitalName") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Who?" SortExpression="WhoVisited">
                                    <EditItemTemplate>
                                        <asp:DropDownList ID="DropDownList7_2" runat="server" 
                                            CssClass="defaultFormElementStyle" SelectedValue='<%# Bind("WhoVisited") %>'>
                                            <asp:ListItem>Staff</asp:ListItem>
                                            <asp:ListItem>Dependant - Wife</asp:ListItem>
                                            <asp:ListItem>Dependant - Husband</asp:ListItem>
                                            <asp:ListItem>Dependant - Child</asp:ListItem>
                                            <asp:ListItem>Dependant - Other</asp:ListItem>
                                        </asp:DropDownList>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label7" runat="server" Text='<%# Bind("WhoVisited") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Summary" SortExpression="BriefSummary">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox6" runat="server" Columns="20" 
                                            Text='<%# Bind("BriefSummary") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("BriefSummary") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Details" 
                                    SortExpression="DetailedDescription">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox5" runat="server" Columns="20" 
                                            CssClass="defaultFormElementStyle" Rows="3" 
                                            Text='<%# Bind("DetailedDescription") %>' TextMode="MultiLine"></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("DetailedDescription") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Dr's Remark" SortExpression="DoctorsRemark">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox4" runat="server" Columns="20" 
                                            CssClass="defaultFormElementStyle" Rows="3" Text='<%# Bind("DoctorsRemark") %>' 
                                            TextMode="MultiLine"></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("DoctorsRemark") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Admitted" SortExpression="DateAttended">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox3" runat="server" Columns="10" 
                                            Text='<%# Bind("DateAttended") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label3" runat="server" 
                                            Text='<%# Common.GetFriendlyDate(CType(Databinder.Eval(Container.DataItem, "DateAttended"), Date)) %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Discharged" SortExpression="DateDischarged">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox2" runat="server" Columns="10" 
                                            Text='<%# Bind("DateDischarged") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label2" runat="server" 
                                            Text='<%# Common.GetFriendlyDate(CType(Databinder.Eval(Container.DataItem, "DateDischarged"), Date)) %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Cost" SortExpression="MedicalExpenses">
                                    <EditItemTemplate>
                                       <asp:TextBox ID="TextBox23" runat="server" Columns="10" 
                                            CssClass="defaultFormElementStyleRightAligned" 
                                            Text='<%# Bind("MedicalExpenses") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        N<asp:Label ID="Label1" runat="server" 
                                            Text='<%# FormatNumber(Databinder.Eval(Container.DataItem, "MedicalExpenses"), 2) %>'></asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle HorizontalAlign="Right" />
                                    <HeaderStyle HorizontalAlign="Right" />
                                </asp:TemplateField>
                                <asp:BoundField DataField="Remark" HeaderText="Remark" SortExpression="Remark" 
                                    Visible="False" />
                            </Columns>
                            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" HorizontalAlign="Left" 
                                VerticalAlign="Top" />
                            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                                HorizontalAlign="Left" VerticalAlign="Top" />
                            <EditRowStyle CssClass="defaultFormElementStyle" />
                            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                            <AlternatingRowStyle BackColor="White" />
                        </asp:GridView>
                   <br />
                        <asp:Label ID="lblAddNew" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Add a New Hospital Visit" CssClass="defaultHeaderTextStyle" 
                            Visible="False"></asp:Label>
                        <asp:DetailsView ID="DetailsView1" runat="server" 
                            AutoGenerateInsertButton="True" AutoGenerateRows="False" CellPadding="4" 
                            DataKeyNames="StaffMedicalId" DataSourceID="dsSqlGetDetail" DefaultMode="Insert" 
                            ForeColor="#333333" GridLines="None" Visible="False" Width="100%" Font-Bold="false" OnItemInserted="DetailsViewItemInserted">
                            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                            <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
                            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" HorizontalAlign="Left" 
                                VerticalAlign="Middle" Wrap="True" />
                            <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" VerticalAlign="Top" 
                                Width="220px" />
                            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                            <Fields>
                                <asp:BoundField DataField="StaffMedicalId" HeaderText="StaffMedicalId" 
                                    InsertVisible="False" ReadOnly="True" SortExpression="StaffMedicalId" />
                                <asp:TemplateField HeaderText="Staff Concerned:" SortExpression="StaffId">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox10" runat="server" Text='<%# Bind("StaffId") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:DropDownList ID="DropDownList5" runat="server" 
                                            CssClass="defaultFormElementStyle" DataSourceID="dsSqlGetSingleStaff" 
                                            DataTextField="StaffDetails" DataValueField="StaffId" 
                                            SelectedValue='<%# Bind("StaffId") %>'>
                                        </asp:DropDownList>
                                        <asp:SqlDataSource ID="dsSqlGetSingleStaff" runat="server" 
                                            ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                            
                                            SelectCommand="SELECT [StaffId], UPPER([Surname]) + ' ' + UPPER([OtherNames]) + ' | ' + UPPER([StaffCode]) + ' | (' + UPPER([DepartmentName]) + ' Department)' AS StaffDetails FROM [HR_Staff_Base] a INNER JOIN [Core_Department] b ON a.Department = left(b.DepartmentName, charindex('.', b.DepartmentName) - 1) WHERE StaffId = @StaffId">
                                            <SelectParameters>
                                                <asp:ControlParameter ControlID="gvMaster" Name="StaffId" 
                                                    PropertyName="SelectedValue" />
                                            </SelectParameters>
                                        </asp:SqlDataSource>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label10" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Which Hospital ?:" 
                                    SortExpression="HospitalId">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox9" runat="server" 
                                            Text='<%# Bind("HospitalId") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:DropDownList ID="DropDownList6" runat="server" 
                                            CssClass="defaultFormElementStyle" DataSourceID="dsSqlHospitals1" 
                                            DataTextField="HospitalName" DataValueField="HospitalId" 
                                            SelectedValue='<%# Bind("HospitalId") %>'>
                                        </asp:DropDownList>
                                        <asp:SqlDataSource ID="dsSqlHospitals1" runat="server" 
                                            ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                            SelectCommand="SELECT [HospitalId], [HospitalName] FROM [HR_Hospital] ORDER BY [HospitalName]">
                                        </asp:SqlDataSource>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label9" runat="server" Text='<%# Bind("HospitalId") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Who Exactly Visited The Hospital?" 
                                    SortExpression="WhoVisited">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox8" runat="server" Text='<%# Bind("WhoVisited") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:DropDownList ID="DropDownList7" runat="server" 
                                            CssClass="defaultFormElementStyle" SelectedValue='<%# Bind("WhoVisited") %>'>
                                            <asp:ListItem>Self</asp:ListItem>
                                            <asp:ListItem>Dependant - Wife</asp:ListItem>
                                            <asp:ListItem>Dependant - Husband</asp:ListItem>
                                            <asp:ListItem>Dependant - Child</asp:ListItem>
                                            <asp:ListItem>Dependant - Other</asp:ListItem>
                                        </asp:DropDownList>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label21" runat="server" Text='<%# Bind("WhoVisited") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Brief Summary of Medical Incident:" 
                                    SortExpression="BriefSummary">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox7" runat="server" Text='<%# Bind("BriefSummary") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox24" runat="server" Columns="40" 
                                            Text='<%# Bind("BriefSummary") %>'></asp:TextBox>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label22" runat="server" Text='<%# Bind("BriefSummary") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Detailed Description:" 
                                    SortExpression="DetailedDescription">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox25" runat="server" 
                                            Text='<%# Bind("DetailedDescription") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox26" runat="server" Columns="50" 
                                            CssClass="defaultFormElementStyle" Rows="5" 
                                            Text='<%# Bind("DetailedDescription") %>' TextMode="MultiLine"></asp:TextBox>
                                   </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label23" runat="server" 
                                            Text='<%# Bind("DetailedDescription") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Doctor's (Additional) Remarks:" 
                                    SortExpression="DoctorsRemark">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox27" runat="server" Text='<%# Bind("DoctorsRemark") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox28" runat="server" Columns="50" 
                                            Text='<%# Bind("DoctorsRemark") %>' CssClass="defaultFormElementStyle" 
                                            Rows="5" TextMode="MultiLine"></asp:TextBox>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label24" runat="server" Text='<%# Bind("DoctorsRemark") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Date Attended/Admitted:" 
                                    SortExpression="DateAttended">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox29" runat="server" Text='<%# Bind("DateAttended") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:DropDownList ID="ddlDateStart_Month" runat="server" AutoPostBack="True" 
                                            CssClass="defaultFormElementStyle">
                                            <asp:ListItem Value="1">January</asp:ListItem>
                                            <asp:ListItem Value="2">February</asp:ListItem>
                                            <asp:ListItem Value="3">March</asp:ListItem>
                                            <asp:ListItem Value="4">April</asp:ListItem>
                                            <asp:ListItem Value="5">May</asp:ListItem>
                                            <asp:ListItem Value="6">June</asp:ListItem>
                                            <asp:ListItem Value="7">July</asp:ListItem>
                                            <asp:ListItem Value="8">August</asp:ListItem>
                                            <asp:ListItem Value="9">September</asp:ListItem>
                                            <asp:ListItem Value="10">October</asp:ListItem>
                                            <asp:ListItem Value="11">November</asp:ListItem>
                                            <asp:ListItem Value="12">December</asp:ListItem>
                                        </asp:DropDownList>
                                        <asp:DropDownList ID="ddlDateStart_Day" runat="server" AutoPostBack="True" 
                                            CssClass="defaultFormElementStyle">
                                            <asp:ListItem value="1">1</asp:ListItem>
                                            <asp:ListItem value="2">2</asp:ListItem>
                                            <asp:ListItem value="3">3</asp:ListItem>
                                            <asp:ListItem value="4">4</asp:ListItem>
                                            <asp:ListItem value="5">5</asp:ListItem>
                                            <asp:ListItem value="6">6</asp:ListItem>
                                            <asp:ListItem value="7">7</asp:ListItem>
                                            <asp:ListItem value="8">8</asp:ListItem>
                                            <asp:ListItem value="9">9</asp:ListItem>
                                            <asp:ListItem value="10">10</asp:ListItem>
                                            <asp:ListItem value="11">11</asp:ListItem>
                                            <asp:ListItem value="12">12</asp:ListItem>
                                            <asp:ListItem value="13">13</asp:ListItem>
                                            <asp:ListItem value="14">14</asp:ListItem>
                                            <asp:ListItem value="15">15</asp:ListItem>
                                            <asp:ListItem value="16">16</asp:ListItem>
                                            <asp:ListItem value="17">17</asp:ListItem>
                                            <asp:ListItem value="18">18</asp:ListItem>
                                            <asp:ListItem value="19">19</asp:ListItem>
                                            <asp:ListItem value="20">20</asp:ListItem>
                                            <asp:ListItem value="21">21</asp:ListItem>
                                            <asp:ListItem value="22">22</asp:ListItem>
                                            <asp:ListItem value="23">23</asp:ListItem>
                                            <asp:ListItem value="24">24</asp:ListItem>
                                            <asp:ListItem value="25">25</asp:ListItem>
                                            <asp:ListItem value="26">26</asp:ListItem>
                                            <asp:ListItem value="27">27</asp:ListItem>
                                            <asp:ListItem value="28">28</asp:ListItem>
                                            <asp:ListItem value="29">29</asp:ListItem>
                                            <asp:ListItem value="30">30</asp:ListItem>
                                            <asp:ListItem value="31">31</asp:ListItem>
                                        </asp:DropDownList>
                                        <asp:DropDownList ID="ddlDateStart_Year" runat="server" AutoPostBack="True" 
                                            CssClass="defaultFormElementStyle">
                                            <asp:ListItem value="2011">2011</asp:ListItem>
                                            <asp:ListItem value="2010">2010</asp:ListItem>
                                            <asp:ListItem value="2009">2009</asp:ListItem>
                                            <asp:ListItem value="2008">2008</asp:ListItem>
                                            <asp:ListItem value="2007">2007</asp:ListItem>
                                            <asp:ListItem value="2006">2006</asp:ListItem>
                                            <asp:ListItem value="2005">2005</asp:ListItem>
                                            <asp:ListItem value="2004">2004</asp:ListItem>
                                            <asp:ListItem value="2003">2003</asp:ListItem>
                                            <asp:ListItem value="2002">2002</asp:ListItem>
                                            <asp:ListItem value="2001">2001</asp:ListItem>
                                            <asp:ListItem value="2000">2000</asp:ListItem>
                                            <asp:ListItem value="1999">1999</asp:ListItem>
                                            <asp:ListItem value="1998">1998</asp:ListItem>
                                            <asp:ListItem value="1997">1997</asp:ListItem>
                                            <asp:ListItem value="1996">1996</asp:ListItem>
                                            <asp:ListItem value="1995">1995</asp:ListItem>
                                            <asp:ListItem value="1994">1994</asp:ListItem>
                                            <asp:ListItem value="1993">1993</asp:ListItem>
                                            <asp:ListItem value="1992">1992</asp:ListItem>
                                            <asp:ListItem value="1991">1991</asp:ListItem>
                                            <asp:ListItem value="1990">1990</asp:ListItem>
                                            <asp:ListItem value="1989">1989</asp:ListItem>
                                            <asp:ListItem value="1988">1988</asp:ListItem>
                                            <asp:ListItem value="1987">1987</asp:ListItem>
                                            <asp:ListItem value="1986">1986</asp:ListItem>
                                            <asp:ListItem value="1985">1985</asp:ListItem>
                                            <asp:ListItem value="1984">1984</asp:ListItem>
                                            <asp:ListItem value="1983">1983</asp:ListItem>
                                            <asp:ListItem value="1982">1982</asp:ListItem>
                                            <asp:ListItem value="1981">1981</asp:ListItem>
                                            <asp:ListItem value="1980">1980</asp:ListItem>
                                            <asp:ListItem value="1979">1979</asp:ListItem>
                                            <asp:ListItem value="1978">1978</asp:ListItem>
                                            <asp:ListItem value="1977">1977</asp:ListItem>
                                            <asp:ListItem value="1976">1976</asp:ListItem>
                                            <asp:ListItem value="1975">1975</asp:ListItem>
                                            <asp:ListItem value="1974">1974</asp:ListItem>
                                            <asp:ListItem value="1973">1973</asp:ListItem>
                                            <asp:ListItem value="1972">1972</asp:ListItem>
                                            <asp:ListItem value="1971">1971</asp:ListItem>
                                            <asp:ListItem value="1970">1970</asp:ListItem>
                                            <asp:ListItem value="1969">1969</asp:ListItem>
                                            <asp:ListItem value="1968">1968</asp:ListItem>
                                            <asp:ListItem value="1967">1967</asp:ListItem>
                                            <asp:ListItem value="1966">1966</asp:ListItem>
                                            <asp:ListItem value="1965">1965</asp:ListItem>
                                            <asp:ListItem value="1964">1964</asp:ListItem>
                                            <asp:ListItem value="1963">1963</asp:ListItem>
                                            <asp:ListItem value="1962">1962</asp:ListItem>
                                            <asp:ListItem value="1961">1961</asp:ListItem>
                                            <asp:ListItem value="1960">1960</asp:ListItem>
                                            <asp:ListItem value="1959">1959</asp:ListItem>
                                            <asp:ListItem value="1958">1958</asp:ListItem>
                                            <asp:ListItem value="1957">1957</asp:ListItem>
                                            <asp:ListItem value="1956">1956</asp:ListItem>
                                            <asp:ListItem value="1955">1955</asp:ListItem>
                                            <asp:ListItem value="1954">1954</asp:ListItem>
                                            <asp:ListItem value="1953">1953</asp:ListItem>
                                            <asp:ListItem value="1952">1952</asp:ListItem>
                                            <asp:ListItem value="1951">1951</asp:ListItem>
                                            <asp:ListItem value="1950">1950</asp:ListItem>
                                            <asp:ListItem value="1949">1949</asp:ListItem>
                                            <asp:ListItem value="1948">1948</asp:ListItem>
                                            <asp:ListItem value="1947">1947</asp:ListItem>
                                            <asp:ListItem value="1946">1946</asp:ListItem>
                                            <asp:ListItem value="1945">1945</asp:ListItem>
                                            <asp:ListItem value="1944">1944</asp:ListItem>
                                            <asp:ListItem value="1943">1943</asp:ListItem>
                                            <asp:ListItem value="1942">1942</asp:ListItem>
                                            <asp:ListItem value="1941">1941</asp:ListItem>
                                            <asp:ListItem value="1940">1940</asp:ListItem>
                                            <asp:ListItem value="1939">1939</asp:ListItem>
                                            <asp:ListItem value="1938">1938</asp:ListItem>
                                            <asp:ListItem value="1937">1937</asp:ListItem>
                                            <asp:ListItem value="1936">1936</asp:ListItem>
                                            <asp:ListItem value="1935">1935</asp:ListItem>
                                            <asp:ListItem value="1934">1934</asp:ListItem>
                                            <asp:ListItem value="1933">1933</asp:ListItem>
                                            <asp:ListItem value="1932">1932</asp:ListItem>
                                            <asp:ListItem value="1931">1931</asp:ListItem>
                                            <asp:ListItem value="1930">1930</asp:ListItem>
                                            <asp:ListItem value="1929">1929</asp:ListItem>
                                            <asp:ListItem value="1928">1928</asp:ListItem>
                                            <asp:ListItem value="1927">1927</asp:ListItem>
                                            <asp:ListItem value="1926">1926</asp:ListItem>
                                            <asp:ListItem value="1925">1925</asp:ListItem>
                                            <asp:ListItem value="1924">1924</asp:ListItem>
                                            <asp:ListItem value="1923">1923</asp:ListItem>
                                            <asp:ListItem value="1922">1922</asp:ListItem>
                                            <asp:ListItem value="1921">1921</asp:ListItem>
                                            <asp:ListItem value="1920">1920</asp:ListItem>
                                            <asp:ListItem value="1919">1919</asp:ListItem>
                                            <asp:ListItem value="1918">1918</asp:ListItem>
                                            <asp:ListItem value="1917">1917</asp:ListItem>
                                            <asp:ListItem value="1916">1916</asp:ListItem>
                                            <asp:ListItem value="1915">1915</asp:ListItem>
                                            <asp:ListItem value="1914">1914</asp:ListItem>
                                            <asp:ListItem value="1913">1913</asp:ListItem>
                                            <asp:ListItem value="1912">1912</asp:ListItem>
                                            <asp:ListItem value="1911">1911</asp:ListItem>
                                        </asp:DropDownList>
                                        <asp:Label ID="lblStartDate" runat="server" Text='<%# Bind("DateAttended") %>'></asp:Label>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label25" runat="server" Text='<%# Bind("DateAttended") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Date Discharged:" 
                                    SortExpression="DateDischarged">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox30" runat="server" Text='<%# Bind("DateDischarged") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:DropDownList ID="ddlDateEnd_Month" runat="server" AutoPostBack="True" 
                                            CssClass="defaultFormElementStyle">
                                            <asp:ListItem Value="1">January</asp:ListItem>
                                            <asp:ListItem Value="2">February</asp:ListItem>
                                            <asp:ListItem Value="3">March</asp:ListItem>
                                            <asp:ListItem Value="4">April</asp:ListItem>
                                            <asp:ListItem Value="5">May</asp:ListItem>
                                            <asp:ListItem Value="6">June</asp:ListItem>
                                            <asp:ListItem Value="7">July</asp:ListItem>
                                            <asp:ListItem Value="8">August</asp:ListItem>
                                            <asp:ListItem Value="9">September</asp:ListItem>
                                            <asp:ListItem Value="10">October</asp:ListItem>
                                            <asp:ListItem Value="11">November</asp:ListItem>
                                            <asp:ListItem Value="12">December</asp:ListItem>
                                        </asp:DropDownList>
                                        <asp:DropDownList ID="ddlDateEnd_Day" runat="server" AutoPostBack="True" 
                                            CssClass="defaultFormElementStyle">
                                            <asp:ListItem value="1">1</asp:ListItem>
                                            <asp:ListItem value="2">2</asp:ListItem>
                                            <asp:ListItem value="3">3</asp:ListItem>
                                            <asp:ListItem value="4">4</asp:ListItem>
                                            <asp:ListItem value="5">5</asp:ListItem>
                                            <asp:ListItem value="6">6</asp:ListItem>
                                            <asp:ListItem value="7">7</asp:ListItem>
                                            <asp:ListItem value="8">8</asp:ListItem>
                                            <asp:ListItem value="9">9</asp:ListItem>
                                            <asp:ListItem value="10">10</asp:ListItem>
                                            <asp:ListItem value="11">11</asp:ListItem>
                                            <asp:ListItem value="12">12</asp:ListItem>
                                            <asp:ListItem value="13">13</asp:ListItem>
                                            <asp:ListItem value="14">14</asp:ListItem>
                                            <asp:ListItem value="15">15</asp:ListItem>
                                            <asp:ListItem value="16">16</asp:ListItem>
                                            <asp:ListItem value="17">17</asp:ListItem>
                                            <asp:ListItem value="18">18</asp:ListItem>
                                            <asp:ListItem value="19">19</asp:ListItem>
                                            <asp:ListItem value="20">20</asp:ListItem>
                                            <asp:ListItem value="21">21</asp:ListItem>
                                            <asp:ListItem value="22">22</asp:ListItem>
                                            <asp:ListItem value="23">23</asp:ListItem>
                                            <asp:ListItem value="24">24</asp:ListItem>
                                            <asp:ListItem value="25">25</asp:ListItem>
                                            <asp:ListItem value="26">26</asp:ListItem>
                                            <asp:ListItem value="27">27</asp:ListItem>
                                            <asp:ListItem value="28">28</asp:ListItem>
                                            <asp:ListItem value="29">29</asp:ListItem>
                                            <asp:ListItem value="30">30</asp:ListItem>
                                            <asp:ListItem value="31">31</asp:ListItem>
                                        </asp:DropDownList>
                                        <asp:DropDownList ID="ddlDateEnd_Year" runat="server" AutoPostBack="True" 
                                            CssClass="defaultFormElementStyle">
                                            <asp:ListItem value="2011">2011</asp:ListItem>
                                            <asp:ListItem value="2010">2010</asp:ListItem>
                                            <asp:ListItem value="2009">2009</asp:ListItem>
                                            <asp:ListItem value="2008">2008</asp:ListItem>
                                            <asp:ListItem value="2007">2007</asp:ListItem>
                                            <asp:ListItem value="2006">2006</asp:ListItem>
                                            <asp:ListItem value="2005">2005</asp:ListItem>
                                            <asp:ListItem value="2004">2004</asp:ListItem>
                                            <asp:ListItem value="2003">2003</asp:ListItem>
                                            <asp:ListItem value="2002">2002</asp:ListItem>
                                            <asp:ListItem value="2001">2001</asp:ListItem>
                                            <asp:ListItem value="2000">2000</asp:ListItem>
                                            <asp:ListItem value="1999">1999</asp:ListItem>
                                            <asp:ListItem value="1998">1998</asp:ListItem>
                                            <asp:ListItem value="1997">1997</asp:ListItem>
                                            <asp:ListItem value="1996">1996</asp:ListItem>
                                            <asp:ListItem value="1995">1995</asp:ListItem>
                                            <asp:ListItem value="1994">1994</asp:ListItem>
                                            <asp:ListItem value="1993">1993</asp:ListItem>
                                            <asp:ListItem value="1992">1992</asp:ListItem>
                                            <asp:ListItem value="1991">1991</asp:ListItem>
                                            <asp:ListItem value="1990">1990</asp:ListItem>
                                            <asp:ListItem value="1989">1989</asp:ListItem>
                                            <asp:ListItem value="1988">1988</asp:ListItem>
                                            <asp:ListItem value="1987">1987</asp:ListItem>
                                            <asp:ListItem value="1986">1986</asp:ListItem>
                                            <asp:ListItem value="1985">1985</asp:ListItem>
                                            <asp:ListItem value="1984">1984</asp:ListItem>
                                            <asp:ListItem value="1983">1983</asp:ListItem>
                                            <asp:ListItem value="1982">1982</asp:ListItem>
                                            <asp:ListItem value="1981">1981</asp:ListItem>
                                            <asp:ListItem value="1980">1980</asp:ListItem>
                                            <asp:ListItem value="1979">1979</asp:ListItem>
                                            <asp:ListItem value="1978">1978</asp:ListItem>
                                            <asp:ListItem value="1977">1977</asp:ListItem>
                                            <asp:ListItem value="1976">1976</asp:ListItem>
                                            <asp:ListItem value="1975">1975</asp:ListItem>
                                            <asp:ListItem value="1974">1974</asp:ListItem>
                                            <asp:ListItem value="1973">1973</asp:ListItem>
                                            <asp:ListItem value="1972">1972</asp:ListItem>
                                            <asp:ListItem value="1971">1971</asp:ListItem>
                                            <asp:ListItem value="1970">1970</asp:ListItem>
                                            <asp:ListItem value="1969">1969</asp:ListItem>
                                            <asp:ListItem value="1968">1968</asp:ListItem>
                                            <asp:ListItem value="1967">1967</asp:ListItem>
                                            <asp:ListItem value="1966">1966</asp:ListItem>
                                            <asp:ListItem value="1965">1965</asp:ListItem>
                                            <asp:ListItem value="1964">1964</asp:ListItem>
                                            <asp:ListItem value="1963">1963</asp:ListItem>
                                            <asp:ListItem value="1962">1962</asp:ListItem>
                                            <asp:ListItem value="1961">1961</asp:ListItem>
                                            <asp:ListItem value="1960">1960</asp:ListItem>
                                            <asp:ListItem value="1959">1959</asp:ListItem>
                                            <asp:ListItem value="1958">1958</asp:ListItem>
                                            <asp:ListItem value="1957">1957</asp:ListItem>
                                            <asp:ListItem value="1956">1956</asp:ListItem>
                                            <asp:ListItem value="1955">1955</asp:ListItem>
                                            <asp:ListItem value="1954">1954</asp:ListItem>
                                            <asp:ListItem value="1953">1953</asp:ListItem>
                                            <asp:ListItem value="1952">1952</asp:ListItem>
                                            <asp:ListItem value="1951">1951</asp:ListItem>
                                            <asp:ListItem value="1950">1950</asp:ListItem>
                                            <asp:ListItem value="1949">1949</asp:ListItem>
                                            <asp:ListItem value="1948">1948</asp:ListItem>
                                            <asp:ListItem value="1947">1947</asp:ListItem>
                                            <asp:ListItem value="1946">1946</asp:ListItem>
                                            <asp:ListItem value="1945">1945</asp:ListItem>
                                            <asp:ListItem value="1944">1944</asp:ListItem>
                                            <asp:ListItem value="1943">1943</asp:ListItem>
                                            <asp:ListItem value="1942">1942</asp:ListItem>
                                            <asp:ListItem value="1941">1941</asp:ListItem>
                                            <asp:ListItem value="1940">1940</asp:ListItem>
                                            <asp:ListItem value="1939">1939</asp:ListItem>
                                            <asp:ListItem value="1938">1938</asp:ListItem>
                                            <asp:ListItem value="1937">1937</asp:ListItem>
                                            <asp:ListItem value="1936">1936</asp:ListItem>
                                            <asp:ListItem value="1935">1935</asp:ListItem>
                                            <asp:ListItem value="1934">1934</asp:ListItem>
                                            <asp:ListItem value="1933">1933</asp:ListItem>
                                            <asp:ListItem value="1932">1932</asp:ListItem>
                                            <asp:ListItem value="1931">1931</asp:ListItem>
                                            <asp:ListItem value="1930">1930</asp:ListItem>
                                            <asp:ListItem value="1929">1929</asp:ListItem>
                                            <asp:ListItem value="1928">1928</asp:ListItem>
                                            <asp:ListItem value="1927">1927</asp:ListItem>
                                            <asp:ListItem value="1926">1926</asp:ListItem>
                                            <asp:ListItem value="1925">1925</asp:ListItem>
                                            <asp:ListItem value="1924">1924</asp:ListItem>
                                            <asp:ListItem value="1923">1923</asp:ListItem>
                                            <asp:ListItem value="1922">1922</asp:ListItem>
                                            <asp:ListItem value="1921">1921</asp:ListItem>
                                            <asp:ListItem value="1920">1920</asp:ListItem>
                                            <asp:ListItem value="1919">1919</asp:ListItem>
                                            <asp:ListItem value="1918">1918</asp:ListItem>
                                            <asp:ListItem value="1917">1917</asp:ListItem>
                                            <asp:ListItem value="1916">1916</asp:ListItem>
                                            <asp:ListItem value="1915">1915</asp:ListItem>
                                            <asp:ListItem value="1914">1914</asp:ListItem>
                                            <asp:ListItem value="1913">1913</asp:ListItem>
                                            <asp:ListItem value="1912">1912</asp:ListItem>
                                            <asp:ListItem value="1911">1911</asp:ListItem>
                                        </asp:DropDownList>
                                        <asp:Label ID="lblEndDate" runat="server" Text='<%# Bind("DateDischarged") %>'></asp:Label>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label26" runat="server" Text='<%# Bind("DateDischarged") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Total Cost Incurred:" 
                                    SortExpression="MedicalExpenses">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox31" runat="server" 
                                            Text='<%# Bind("MedicalExpenses") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        N
                                        <asp:TextBox ID="TextBox32" runat="server" Columns="10" 
                                            CssClass="defaultFormElementStyleRightAligned" 
                                            Text='<%# Bind("MedicalExpenses") %>'></asp:TextBox>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label27" runat="server" Text='<%# Bind("MedicalExpenses") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Remark:" SortExpression="Remark">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Remark") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <InsertItemTemplate>
                                        <asp:TextBox ID="TextBox33" runat="server" Columns="50" 
                                            CssClass="defaultFormElementStyle" Rows="5" Text='<%# Bind("Remark") %>' 
                                            TextMode="MultiLine"></asp:TextBox>
                                    </InsertItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label28" runat="server" Text='<%# Bind("Remark") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Fields>
                            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                            <AlternatingRowStyle BackColor="White" />
                        </asp:DetailsView>
                   </ItemTemplate>
                    <HeaderStyle HorizontalAlign="Left" VerticalAlign="Top" />
                    <ItemStyle HorizontalAlign="Left" VerticalAlign="Top" />
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <RowStyle HorizontalAlign="Left" VerticalAlign="Top" BackColor="#FFFBD6" 
                ForeColor="#333333" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                HorizontalAlign="Left" />
            <EditRowStyle CssClass="defaultFormElementStyle" />
            <AlternatingRowStyle BackColor="White" />
        </asp:GridView>
                    <asp:SqlDataSource ID="dsSqlGetDetail" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                        SelectCommand="SELECT [StaffMedicalId], [StaffId], a.[HospitalId], b.HospitalName, [WhoVisited], [BriefSummary], [DetailedDescription], [DoctorsRemark], [DateAttended], [DateDischarged], [MedicalExpenses], a.[Remark] FROM [dbo].[HR_Staff_Medical] a INNER JOIN dbo.[HR_Hospital] b ON a.HospitalId = b.HospitalId WHERE StaffId = @StaffId" 
                        DeleteCommand="STP_HR_DELETE_HR_Staff_Medical" 
                        DeleteCommandType="StoredProcedure" 
                        InsertCommand="STP_HR_INSERT_HR_Staff_Medical" 
                        InsertCommandType="StoredProcedure" 
                        UpdateCommand="STP_HR_UPDATE_HR_Staff_Medical" 
                        UpdateCommandType="StoredProcedure">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="gvMaster" Name="StaffId" 
                                PropertyName="SelectedValue" />
                        </SelectParameters>
                        <DeleteParameters>
                            <asp:Parameter Name="StaffMedicalId" Type="Int32" />
                        </DeleteParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="StaffMedicalId" Type="Int32" />
                            <asp:Parameter Name="StaffId" Type="Int32" />
                            <asp:Parameter Name="HospitalId" Type="Int32" />
                            <asp:Parameter Name="WhoVisited" Type="String" />
                            <asp:Parameter Name="BriefSummary" Type="String" />
                            <asp:Parameter Name="DetailedDescription" Type="String" />
                            <asp:Parameter Name="DoctorsRemark" Type="String" />
                            <asp:Parameter Name="DateAttended" Type="DateTime" />
                            <asp:Parameter Name="DateDischarged" Type="DateTime" />
                            <asp:Parameter Name="MedicalExpenses" Type="Decimal" />
                            <asp:Parameter Name="Remark" Type="String" />
                        </UpdateParameters>
                        <InsertParameters>
                            <asp:Parameter Direction="InputOutput" Name="StaffMedicalId" Type="Int32" />
                            <asp:Parameter Name="StaffId" Type="Int32" />
                            <asp:Parameter Name="HospitalId" Type="Int32" />
                            <asp:Parameter Name="WhoVisited" Type="String" />
                            <asp:Parameter Name="BriefSummary" Type="String" />
                            <asp:Parameter Name="DetailedDescription" Type="String" />
                            <asp:Parameter Name="DoctorsRemark" Type="String" />
                            <asp:Parameter Name="DateAttended" Type="DateTime" />
                            <asp:Parameter Name="DateDischarged" Type="DateTime" />
                            <asp:Parameter Name="MedicalExpenses" Type="Decimal" />
                            <asp:Parameter Name="Remark" Type="String" />
                        </InsertParameters>
                    </asp:SqlDataSource>
        <asp:SqlDataSource ID="dsoUsers" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
            
                        SelectCommand="SELECT [StaffId], [StaffGUID], [StaffCode], [MaritalStatus], [WeddingDate], [Gender], [DateOfBirth], [ConfirmationStatus], [RetirementStatus], [Surname], [OtherNames], [Department], right(b.DepartmentName, len(b.DepartmentName) - charindex('.', b.DepartmentName)) AS DepartmentName, [DateOfEmployment], [Email], a.[DesignationId], c.DesignationName, a.[JobLevelId], d.JobLevelName, a.[LocationId], e.LocationName, [Residence], [PermanentResidence], [Telephone], a.[ReligionId], f.ReligionName, [Hometown], a.[LGAOfOriginId], g.LgaName + ' LGA (' + h.StateName + ')' AS LgaName, a.[BankId], i.BankName, [BankAccountNumber], [Visa], [EyeColour], [Height], [Weight], [TrouserLength], [ShoeSize], [BloodGroup], [Genotype], [Hobbies], a.[AreaOfInterest], [VisaType], [Coop_MonthlyDeduction], [Coop_LoanRepayment], [MaxMedical], [NextOfKinName], [NextOfKinAddress], [NextOfKinRelationship] FROM [dbo].[HR_Staff_Base] a INNER JOIN dbo.[Core_Department] b ON a.Department = left(b.DepartmentName, charindex('.', b.DepartmentName) - 1) INNER JOIN dbo.[HR_Designation] c ON a.DesignationId = c.DesignationId INNER JOIN dbo.[HR_JobLevel] d ON a.JobLevelId = d.JobLevelId INNER JOIN dbo.[HR_Location] e ON a.LocationId = e.LocationId INNER JOIN dbo.[HR_Religion] f ON a.ReligionId = f.ReligionId INNER JOIN dbo.[Core_Lga] g ON a.LgaOfOriginId = g.LgaId INNER JOIN dbo.[Core_State] h ON g.StateId = h.StateId INNER JOIN dbo.[HR_Bank] i ON a.BankId = i.BankId ORDER BY Surname, OtherNames  ">
        </asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td colspan="2">&nbsp;
                    </td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
