<%@ Page Language="VB" AutoEventWireup="false" CodeFile="input_payroll_loan.aspx.vb" Inherits="modules_hr_input_payroll_loan" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>Untitled Page</title>
    <link href="../../StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <table border="0" width="100%">
            <tr>
                <td colspan="2">
						<asp:Label ID="lblHeader" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Edit Previous Loans"></asp:Label></td>
            </tr>
            <tr>
                <td width="3%">&nbsp;
                    </td>
                <td>
                    <asp:GridView ID="gvUsers" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="True"
                        CssClass="noBorderedMenuTable" 
                        DataSourceID="dsSqlGetData" Width="1000px" CellPadding="4" ForeColor="#333333" 
                        GridLines="None" 
                        
                        EmptyDataText="&amp;nbsp;&lt;br /&gt;No records to display.&lt;br /&gt;&amp;nbsp;" 
                        DataKeyNames="StaffCompanyLoanId" 
                        AutoGenerateSelectButton="True" AutoGenerateDeleteButton="True" 
                        AllowSorting="True">
                        <Columns>
                            <asp:BoundField DataField="StaffCompanyLoanId" HeaderText="Id" 
                                InsertVisible="False" ReadOnly="True" 
                                SortExpression="StaffCompanyLoanId" />
                            <asp:TemplateField HeaderText="Staff Id" SortExpression="StaffId">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList5_2" runat="server" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsSqlGetSingleStaff_2" 
                                        DataTextField="StaffDetails" DataValueField="StaffId" 
                                        SelectedValue='<%# Bind("StaffId") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="dsSqlGetSingleStaff_2" runat="server" 
                                        ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                        SelectCommand="SELECT [StaffId], UPPER([Surname]) + ' ' + UPPER([OtherNames]) + ' | ' + UPPER([StaffCode]) + ' | (' + UPPER([DepartmentName]) + ' Department)' AS StaffDetails FROM [HR_Staff_Base] a INNER JOIN [Core_Department] b ON a.Department = left(b.DepartmentName, charindex('.', b.DepartmentName) - 1) ORDER BY StaffDetails">
                                    </asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("StaffDetails") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Entry Date" SortExpression="EntryDate">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox2" runat="server" Columns="30" 
                                        Text='<%# Bind("EntryDate") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label6" runat="server" 
                                        Text='<%# Common.GetFriendlyDate(CType(Databinder.Eval(Container.DataItem, "EntryDate"), Date)) %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Loan Amount" SortExpression="LoanAmount">
                                <EditItemTemplate>
                                    N
                                    <asp:TextBox ID="TextBox3" runat="server" Columns="10" 
                                        CssClass="defaultFormElementStyleRightAligned" Text='<%# Bind("LoanAmount") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    N
                                    <asp:Label ID="Label3" runat="server" Text='<%# FormatNumber(CType(Databinder.Eval(Container.DataItem, "LoanAmount"), Double), 2) %>'></asp:Label>
                                </ItemTemplate>
                                <HeaderStyle HorizontalAlign="Right" />
                                <ItemStyle HorizontalAlign="Right" />
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Instalments" SortExpression="Instalments">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox4" runat="server" Columns="5" 
                                        CssClass="defaultFormElementStyleRightAligned" 
                                        Text='<%# Bind("Instalments") %>'></asp:TextBox>
                                    &nbsp;times
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("Instalments") %>'></asp:Label>
                                    &nbsp;times
                                </ItemTemplate>
                                <HeaderStyle HorizontalAlign="Right" />
                                <ItemStyle HorizontalAlign="Right" />
                            </asp:TemplateField>
                            <asp:BoundField DataField="Remark" HeaderText="Remark" SortExpression="Remark" 
                                Visible="False" />
                        </Columns>
                        <RowStyle HorizontalAlign="Left" VerticalAlign="Middle" BackColor="#FFFBD6" 
                            ForeColor="#333333" />
                        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" 
                            HorizontalAlign="Left" VerticalAlign="Top" />
                        <EditRowStyle CssClass="defaultFormElementStyle" />
                        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                        <AlternatingRowStyle BackColor="White" />
                    </asp:GridView>
                    <asp:SqlDataSource ID="dsSqlGetData" runat="server" ConnectionString="<%$ ConnectionStrings:iTecon %>"
                        SelectCommand="SELECT [StaffCompanyLoanId], a.[StaffId], UPPER(b.[Surname]) + ' ' + UPPER(b.[OtherNames]) + ' | ' + UPPER(b.[StaffCode]) + ' | (' + UPPER(c.[DepartmentName]) + ' Department)' AS StaffDetails, a.[EntryDate], [LoanAmount], [Instalments], a.[Remark] FROM [dbo].[HR_PAYROLL_Staff_Company_Loan] a INNER JOIN dbo.[HR_Staff_Base] b ON a.StaffId = b.StaffId INNER JOIN dbo.[Core_Department] c ON b.Department = left(c.DepartmentName, charindex('.', c.DepartmentName) - 1) " 
                        DeleteCommand="STP_HR_DELETE_HR_PAYROLL_Staff_Company_Loan" 
                        DeleteCommandType="StoredProcedure" 
                        InsertCommand="STP_HR_INSERT_HR_PAYROLL_Staff_Company_Loan" 
                        InsertCommandType="StoredProcedure" 
                        UpdateCommand="STP_HR_UPDATE_HR_PAYROLL_Staff_Company_Loan" 
                        UpdateCommandType="StoredProcedure">
                        <DeleteParameters>
                            <asp:Parameter Name="StaffCompanyLoanId" Type="Int32" />
                        </DeleteParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="StaffCompanyLoanId" Type="Int32" />
                            <asp:Parameter Name="StaffId" Type="Int32" />
                            <asp:Parameter Name="EntryDate" Type="DateTime" />
                            <asp:Parameter Name="LoanAmount" Type="Decimal" />
                            <asp:Parameter Name="Instalments" Type="Int32" />
                            <asp:Parameter Name="Remark" Type="String" />
                        </UpdateParameters>
                        <InsertParameters>
                            <asp:Parameter Direction="InputOutput" Name="StaffCompanyLoanId" 
                                Type="Int32" />
                            <asp:Parameter Name="StaffId" Type="Int32" />
                            <asp:Parameter Name="EntryDate" Type="DateTime" />
                            <asp:Parameter Name="LoanAmount" Type="Decimal" />
                            <asp:Parameter Name="Instalments" Type="Int32" />
                            <asp:Parameter Name="Remark" Type="String" />
                        </InsertParameters>
                    </asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                    <hr color="black" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <br />
                    <asp:Label ID="lblAddNew" runat="server" Font-Bold="True" Font-Size="Small" 
                        Text=":: Add a New Loan"></asp:Label></td>
            </tr>
            <tr>
                <td>&nbsp;
                    </td>
                <td>
                    <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False"
                        DataSourceID="dsSqlGetData" DefaultMode="Insert" Width="900px" 
                        CellPadding="4" ForeColor="#333333" GridLines="None" 
                        AutoGenerateInsertButton="True" DataKeyNames="StaffCompanyLoanId">
                        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
                        <RowStyle HorizontalAlign="Left" VerticalAlign="Middle" Wrap="True" 
                            BackColor="#FFFBD6" ForeColor="#333333" />
                        <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" Width="220px" 
                            VerticalAlign="Top" />
                        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                        <Fields>
                            <asp:BoundField DataField="StaffCompanyLoanId" HeaderText="StaffCompanyLoanId" 
                                InsertVisible="False" ReadOnly="True" 
                                SortExpression="StaffCompanyLoanId" />
                            <asp:TemplateField HeaderText="Staff Concerned:" SortExpression="StaffId">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("StaffId") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:DropDownList ID="DropDownList5" runat="server" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsSqlGetSingleStaff" 
                                        DataTextField="StaffDetails" DataValueField="StaffId" 
                                        SelectedValue='<%# Bind("StaffId") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="dsSqlGetSingleStaff" runat="server" 
                                        ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                        SelectCommand="SELECT [StaffId], UPPER([Surname]) + ' ' + UPPER([OtherNames]) + ' | ' + UPPER([StaffCode]) + ' | (' + UPPER([DepartmentName]) + ' Department)' AS StaffDetails FROM [HR_Staff_Base] a INNER JOIN [Core_Department] b ON a.Department = left(b.DepartmentName, charindex('.', b.DepartmentName) - 1) ORDER BY StaffDetails">
                                    </asp:SqlDataSource>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("StaffId") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Entry Date:" SortExpression="EntryDate">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("EntryDate") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:DropDownList ID="DropDownList6" runat="server" 
                                        CssClass="defaultFormElementStyle" DataSourceID="dsSqlGetDate" 
                                        DataTextField="CurrentDate" DataValueField="CurrentDate" 
                                        SelectedValue='<%# Bind("EntryDate") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="dsSqlGetDate" runat="server" 
                                        ConnectionString="<%$ ConnectionStrings:iTecon %>" 
                                        SelectCommand="SELECT GetDate() AS CurrentDate"></asp:SqlDataSource>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label5" runat="server" Text='<%# Bind("EntryDate") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Loan Amount:" SortExpression="LoanAmount">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("LoanAmount") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    N
                                    <asp:TextBox ID="TextBox2" runat="server" Columns="10" 
                                        CssClass="defaultFormElementStyleRightAligned" Text='<%# Bind("LoanAmount") %>'></asp:TextBox>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("LoanAmount") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="No of Instalments:" SortExpression="Instalments">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("Instalments") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox4" runat="server" Columns="5" 
                                        CssClass="defaultFormElementStyleRightAligned" 
                                        Text='<%# Bind("Instalments") %>'></asp:TextBox>
                                    &nbsp;times
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("Instalments") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Remark:" SortExpression="Remark">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("Remark") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <InsertItemTemplate>
                                    <asp:TextBox ID="TextBox3" runat="server" Columns="50" 
                                        CssClass="defaultFormElementStyle" Rows="5" Text='<%# Bind("Remark") %>' 
                                        TextMode="MultiLine"></asp:TextBox>
                                </InsertItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("Remark") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Fields>
                        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <AlternatingRowStyle BackColor="White" />
                    </asp:DetailsView>
                    &nbsp; &nbsp;&nbsp;</td>
            </tr>
            <tr>
                <td colspan="2">&nbsp;
                    </td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
