
' Generated by MyGeneration Version # (1.2.0.2)

Imports System
Imports System.Data
Imports System.Data.Common

NameSpace DbEntities

Public Class Core_Menu 
	Inherits _Core_Menu

	Public Sub New()
		Me.DefaultCommandType = CommandType.Text
	End Sub

End Class

End NameSpace
