
' Generated by MyGeneration Version # (1.2.0.2)

Imports System
Imports System.Data
Imports System.Data.Common
Imports Microsoft.Practices.EnterpriseLibrary.Data
Imports NCI.EasyObjects

NameSpace DbEntities

Public Class Core_Role 
        Inherits _Core_Role
        Dim _db As Database = GetDatabase()

	Public Sub New()
		Me.DefaultCommandType = CommandType.Text
	End Sub
        Public Function SelectAll() As Boolean
            Dim storedProcedureName As String = "STP_METADATA_SELECT_ROLE_ALL"
            Dim dbCommand As DbCommand = _db.GetStoredProcCommand(storedProcedureName)

            Return MyBase.LoadFromSql(dbCommand)
        End Function
    End Class
End NameSpace
