
' Generated by MyGeneration Version # (1.2.0.2)

Imports System
Imports System.Data
Imports System.Data.Common
Imports Microsoft.Practices.EnterpriseLibrary.Data
Imports NCI.EasyObjects

NameSpace DbEntities

Public Class Core_RoleMenu 
	Inherits _Core_RoleMenu
        Dim _db As Database = GetDatabase()

	Public Sub New()
		Me.DefaultCommandType = CommandType.Text
	End Sub
        Public Function GetRoleMenus(ByVal roleId As Int32) As Boolean
            Dim storedProcedureName As String = "STP_METADATA_SELECT_MENU_PER_ROLE_BY_ROLEID"
            Dim dbCommand As DbCommand = _db.GetStoredProcCommand(storedProcedureName)

            ' Add procedure parameters
            _db.AddInParameter(dbCommand, DbEntities.Core_RoleMenuSchema.RoleId.FieldName, DbType.Int32, roleId)

            Return MyBase.LoadFromSql(dbCommand)
        End Function
End Class

End NameSpace
