'===============================================================================
'  Generated From - VbNet_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject 
'      Inherits _YourObject
'
'  End Class
'
'===============================================================================

' Generated by MyGeneration Version # (1.2.0.2)

Imports System
Imports System.Data
Imports System.Data.Common
Imports System.Configuration
Imports System.Collections
Imports System.Collections.Specialized
Imports System.Xml
Imports System.IO

Imports Microsoft.Practices.EnterpriseLibrary.Data
Imports NCI.EasyObjects


NameSpace DbEntities

#Region " Schema "

Public Class Core_RoleUserSchema
	Inherits NCI.EasyObjects.Schema

    Private Shared _entries As ArrayList
	Public Shared RoleUserId As New SchemaItem("RoleUserId", DbType.Int32, True, False, False, True, False, False)
	Public Shared RoleId As New SchemaItem("RoleId", DbType.Int32, False, False, False, False, False, False)
	Public Shared UserId As New SchemaItem("UserId", DbType.Int64, False, False, False, False, False, False)

    Public Overrides ReadOnly Property SchemaEntries() As ArrayList
        Get
            If _entries Is Nothing Then
                _entries = New ArrayList()
				_entries.Add(Core_RoleUserSchema.RoleUserId)
				_entries.Add(Core_RoleUserSchema.RoleId)
				_entries.Add(Core_RoleUserSchema.UserId)
			End If
            Return _entries
        End Get
    End Property

	Public Shared ReadOnly Property HasAutoKey() As Boolean
        Get
            Return True
        End Get
    End Property

    Public Shared ReadOnly Property HasRowID() As Boolean
        Get
            Return False
        End Get
    End Property

End Class

#End Region

Public MustInherit Class _Core_RoleUser
    Inherits EasyObject

    Sub New()
        Dim _schema As New Core_RoleUserSchema()
        Me.SchemaEntries = _schema.SchemaEntries
		Me.SchemaGlobal = "dbo"
    End Sub

	Public Overrides Sub FlushData()
		Me._whereClause = Nothing
		Me._aggregateClause = Nothing
		MyBase.FlushData()
	End Sub
		
	''' <summary>
	''' Loads the business object with info from the database, based on the requested primary key.
	''' </summary>
	''' <param name="RoleUserId"></param>
	''' <returns>A Boolean indicating success or failure of the query</returns>
	Public Function LoadByPrimaryKey(ByVal RoleUserId As Integer) As Boolean
		
		Select Case Me.DefaultCommandType
			Case CommandType.StoredProcedure
				Dim parameters As ListDictionary = New ListDictionary

				' Add in parameters
				parameters.Add(Core_RoleUserSchema.RoleUserId.FieldName, RoleUserId)

				Return MyBase.LoadFromSql(Me.SchemaStoredProcedureWithSeparator & "STP_METADATA_Select_Core_RoleUser", parameters, CommandType.StoredProcedure)
				
			Case CommandType.Text
                Me.Query.ClearAll()
                Me.Where.WhereClauseReset()
				Me.Where.RoleUserId.Value = RoleUserId
				Return Me.Query.Load()

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select
		
	End Function

    ''' <summary>
    ''' Loads all records from the table.
    ''' </summary>
    ''' <returns>A Boolean indicating success or failure of the query</returns>
    Public Function LoadAll() As Boolean
	
		Select Case Me.DefaultCommandType
		
			Case CommandType.StoredProcedure
				Dim parameters As ListDictionary = Nothing
				Return MyBase.LoadFromSql(Me.SchemaStoredProcedureWithSeparator & "STP_METADATA_SelectAll_Core_RoleUser", parameters, CommandType.StoredProcedure)
				
			Case CommandType.Text
                Me.Query.ClearAll()
                Me.Where.WhereClauseReset()
				Return Me.Query.Load()
			
			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

    End Function

    ''' <summary>
    ''' Adds a new record to the internal table.
    ''' </summary>
	Public Overrides Sub AddNew()
		MyBase.AddNew()
		Me.ApplyDefaults()
	End Sub

	''' <summary>
	''' Apply any default values to columns
	''' </summary>
	Protected Overrides Sub ApplyDefaults()
	End Sub

    Protected Overrides Function GetInsertCommand(commandType As CommandType) As DbCommand
	
		Dim dbCommand As DbCommand
		
        ' Create the Database object, using the default database service. The
        ' default database service is determined through configuration.
        Dim db As Database = GetDatabase()
	
		Select Case commandType
		
			Case CommandType.StoredProcedure
				Dim sqlCommand As String = Me.SchemaStoredProcedureWithSeparator & "STP_METADATA_Insert_Core_RoleUser"
				dbCommand = db.GetStoredProcCommand(sqlCommand)
				
				db.AddParameter(dbCommand, "RoleUserId", DbType.Int32, 0, ParameterDirection.Output, True, 0, 0, "RoleUserId", DataRowVersion.Default, Convert.DBNull)
				CreateParameters(db, dbCommand)

			Case CommandType.Text
                Me.Query.ClearAll()
				Me.Where.WhereClauseReset()
				For Each item As SchemaItem In Me.SchemaEntries
                    If Not item.IsComputed Then
                        If (item.IsAutoKey AndAlso Me.IdentityInsert) OrElse Not item.IsAutoKey Then
                            Me.Query.AddInsertColumn(item)
                        End If
                    End If
				Next
				dbCommand = Me.Query.GetInsertCommandWrapper()

				dbCommand.Parameters.Clear()
				If Me.IdentityInsert Then
					db.AddInParameter(dbCommand, "RoleUserId", DbType.Int32, "RoleUserId", DataRowVersion.Default)
				Else
					db.AddParameter(dbCommand, "RoleUserId", DbType.Int32, 0, ParameterDirection.Output, True, 0, 0, "RoleUserId", DataRowVersion.Default, Convert.DBNull)
				End If

				CreateParameters(db, dbCommand)

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

        Return dbCommand

    End Function

    Protected Overrides Function GetUpdateCommand(commandType As CommandType) As DbCommand
	
		Dim dbCommand As DbCommand

        ' Create the Database object, using the default database service. The
        ' default database service is determined through configuration.
        Dim db As Database = GetDatabase()
	
		Select Case commandType
		
			Case CommandType.StoredProcedure
				Dim sqlCommand As String = Me.SchemaStoredProcedureWithSeparator & "STP_METADATA_Update_Core_RoleUser"
				dbCommand = db.GetStoredProcCommand(sqlCommand)
		
				db.AddInParameter(dbCommand, "RoleUserId", DbType.Int32, "RoleUserId", DataRowVersion.Current)
				CreateParameters(db, dbCommand)

			Case CommandType.Text
                Me.Query.ClearAll()
				For Each item As SchemaItem In Me.SchemaEntries
					If Not (item.IsAutoKey OrElse item.IsComputed)
						Me.Query.AddUpdateColumn(item)
					End If
				Next

				Me.Where.WhereClauseReset()
				Me.Where.RoleUserId.Operator = WhereParameter.Operand.Equal
				dbCommand = Me.Query.GetUpdateCommandWrapper()

				dbCommand.Parameters.Clear()
				CreateParameters(db, dbCommand)
				db.AddInParameter(dbCommand, "RoleUserId", DbType.Int32, "RoleUserId", DataRowVersion.Current)

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

        Return dbCommand

    End Function

    Protected Overrides Function GetDeleteCommand(commandType As CommandType) As DbCommand
	
		Dim dbCommand As DbCommand

        ' Create the Database object, using the default database service. The
        ' default database service is determined through configuration.
        Dim db As Database = GetDatabase()
	
		Select Case commandType
		
			Case CommandType.StoredProcedure
				Dim sqlCommand As String = Me.SchemaStoredProcedureWithSeparator & "STP_METADATA_Delete_Core_RoleUser"
				dbCommand = db.GetStoredProcCommand(sqlCommand)
		
				' Add primary key parameters
				db.AddInParameter(dbCommand, "RoleUserId", DbType.Int32, "RoleUserId", DataRowVersion.Current)

			Case CommandType.Text
                Me.Query.ClearAll()
				Me.Where.WhereClauseReset()
				Me.Where.RoleUserId.Operator = WhereParameter.Operand.Equal
				dbCommand = Me.Query.GetDeleteCommandWrapper()

				dbCommand.Parameters.Clear()
				db.AddInParameter(dbCommand, "RoleUserId", DbType.Int32, "RoleUserId", DataRowVersion.Current)

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

        Return dbCommand

    End Function

    Private Sub CreateParameters(ByVal db As Database, ByVal dbCommand As DbCommand)
		
		db.AddInParameter(dbCommand, "RoleId", DbType.Int32, "RoleId", DataRowVersion.Current)
		db.AddInParameter(dbCommand, "UserId", DbType.Int64, "UserId", DataRowVersion.Current)

    End Sub

#Region " Properties "

	Public Overridable Property RoleUserId() As Integer
        Get
			Return Me.GetInteger(Core_RoleUserSchema.RoleUserId.FieldName)
      End Get
        Set(ByVal Value As Integer)
			Me.SetInteger(Core_RoleUserSchema.RoleUserId.FieldName, Value)
      End Set
    End Property

	Public Overridable Property RoleId() As Integer
        Get
			Return Me.GetInteger(Core_RoleUserSchema.RoleId.FieldName)
      End Get
        Set(ByVal Value As Integer)
			Me.SetInteger(Core_RoleUserSchema.RoleId.FieldName, Value)
      End Set
    End Property

	Public Overridable Property UserId() As Long
        Get
			Return Me.GetLong(Core_RoleUserSchema.UserId.FieldName)
      End Get
        Set(ByVal Value As Long)
			Me.SetLong(Core_RoleUserSchema.UserId.FieldName, Value)
      End Set
    End Property

    Public Overrides ReadOnly Property TableName() As String
        Get
            Return "Core_RoleUser"
        End Get
    End Property

#End Region

#Region " String Properties "
		Public Overridable Property s_RoleUserId As String
			Get
				If Me.IsColumnNull(Core_RoleUserSchema.RoleUserId.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(Core_RoleUserSchema.RoleUserId.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(Core_RoleUserSchema.RoleUserId.FieldName)
				Else
					Me.RoleUserId = MyBase.SetIntegerAsString(Core_RoleUserSchema.RoleUserId.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_RoleId As String
			Get
				If Me.IsColumnNull(Core_RoleUserSchema.RoleId.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(Core_RoleUserSchema.RoleId.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(Core_RoleUserSchema.RoleId.FieldName)
				Else
					Me.RoleId = MyBase.SetIntegerAsString(Core_RoleUserSchema.RoleId.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_UserId As String
			Get
				If Me.IsColumnNull(Core_RoleUserSchema.UserId.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetLongAsString(Core_RoleUserSchema.UserId.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(Core_RoleUserSchema.UserId.FieldName)
				Else
					Me.UserId = MyBase.SetLongAsString(Core_RoleUserSchema.UserId.FieldName, Value)
				End If
			End Set
		End Property


#End Region

#Region " Where Clause "
    Public Class WhereClause

        Public Sub New(ByVal entity As EasyObject)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region " TearOff's "
		Public class TearOffWhereParameter
		
			Private _clause as WhereClause
			
			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub

			Public ReadOnly Property RoleUserId() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(Core_RoleUserSchema.RoleUserId)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property RoleId() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(Core_RoleUserSchema.RoleId)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property UserId() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(Core_RoleUserSchema.UserId)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

	End Class
	
	#End Region	

		Public ReadOnly Property RoleUserId() As WhereParameter 
			Get
				If _RoleUserId_W Is Nothing Then
					_RoleUserId_W = TearOff.RoleUserId
				End If
				Return _RoleUserId_W
			End Get
		End Property

		Public ReadOnly Property RoleId() As WhereParameter 
			Get
				If _RoleId_W Is Nothing Then
					_RoleId_W = TearOff.RoleId
				End If
				Return _RoleId_W
			End Get
		End Property

		Public ReadOnly Property UserId() As WhereParameter 
			Get
				If _UserId_W Is Nothing Then
					_UserId_W = TearOff.UserId
				End If
				Return _UserId_W
			End Get
		End Property

		Private _RoleUserId_W As WhereParameter = Nothing
		Private _RoleId_W As WhereParameter = Nothing
		Private _UserId_W As WhereParameter = Nothing

		Public Sub WhereClauseReset()

		_RoleUserId_W = Nothing
		_RoleId_W = Nothing
		_UserId_W = Nothing
			Me._entity.Query.FlushWhereParameters()

		End Sub
	
		Private _entity As EasyObject
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region " Aggregate Clause "
    Public Class AggregateClause

        Public Sub New(ByVal entity As EasyObject)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region " TearOff's "
		Public class TearOffAggregateParameter
		
			Private _clause as AggregateClause
			
			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub

			Public ReadOnly Property RoleUserId() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(Core_RoleUserSchema.RoleUserId)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property RoleId() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(Core_RoleUserSchema.RoleId)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property UserId() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(Core_RoleUserSchema.UserId)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

	End Class
	
	#End Region	

		Public ReadOnly Property RoleUserId() As AggregateParameter 
			Get
				If _RoleUserId_W Is Nothing Then
					_RoleUserId_W = TearOff.RoleUserId
				End If
				Return _RoleUserId_W
			End Get
		End Property

		Public ReadOnly Property RoleId() As AggregateParameter 
			Get
				If _RoleId_W Is Nothing Then
					_RoleId_W = TearOff.RoleId
				End If
				Return _RoleId_W
			End Get
		End Property

		Public ReadOnly Property UserId() As AggregateParameter 
			Get
				If _UserId_W Is Nothing Then
					_UserId_W = TearOff.UserId
				End If
				Return _UserId_W
			End Get
		End Property

		Private _RoleUserId_W As AggregateParameter = Nothing
		Private _RoleId_W As AggregateParameter = Nothing
		Private _UserId_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_RoleUserId_W = Nothing
		_RoleId_W = Nothing
		_UserId_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As EasyObject
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

End Class

End NameSpace


